class CalibrationRunsController < ApplicationController
  def index
    @calibration_runs = CalibrationRun.order(created_at: :desc)
  end

  def show
    @calibration_run = CalibrationRun.find(params[:id])
    @result = parse_result(@calibration_run.result_json)
  end

  def new
    @calibration_run = CalibrationRun.new
    @benchmarks = StellarPop::Calibration::BenchmarkCatalog.all
  end

  def create
    @calibration_run = CalibrationRun.new(calibration_run_params)
    @calibration_run.name = autogenerated_name if @calibration_run.name.to_s.strip.empty?
    @calibration_run.status = "pending"

    if @calibration_run.save
      CalibrationRunJob.perform_later(@calibration_run.id)
      redirect_to @calibration_run, notice: "Calibration run created."
    else
      @benchmarks = StellarPop::Calibration::BenchmarkCatalog.all
      render :new, status: :unprocessable_entity
    end
  end

  private

  def calibration_run_params
    params.require(:calibration_run).permit(:name)
  end

  def parse_result(result_json)
    JSON.parse(result_json.presence || "{}")
  rescue JSON::ParserError
    {}
  end

  def autogenerated_name
    "calibration_#{Time.current.strftime('%Y%m%d_%H%M%S')}"
  end
end
