class CalibrationRunsController < ApplicationController
  def index
    @calibration_runs = CalibrationRun.order(created_at: :desc)
  end

  def show
    @calibration_run = CalibrationRun.find(params[:id])
    @result = parse_result(@calibration_run.result_json)
  end

  def new
    @calibration_run = CalibrationRun.new
    @benchmarks = StellarPop::Calibration::BenchmarkCatalog.all
  end

  def create
    @calibration_run = CalibrationRun.new(calibration_run_params)
    @calibration_run.name = autogenerated_name if @calibration_run.name.to_s.strip.empty?
    @calibration_run.status = "pending"

    if @calibration_run.save
      CalibrationRunJob.perform_later(
        @calibration_run.id,
        benchmark_keys: selected_benchmark_keys,
        fast_mode: fast_mode_enabled?
      )
      redirect_to @calibration_run, notice: "Benchmark run created."
    else
      @benchmarks = StellarPop::Calibration::BenchmarkCatalog.all
      render :new, status: :unprocessable_entity
    end
  end

  private

  def calibration_run_params
    params.require(:calibration_run).permit(:name)
  end

  def parse_result(result_json)
    JSON.parse(result_json.presence || "{}")
  rescue JSON::ParserError
    {}
  end

  def autogenerated_name
    "bm_#{Time.current.strftime('%Y%m%d_%H%M%S')}"
  end

  def selected_benchmark_keys
    all_keys = StellarPop::Calibration::BenchmarkCatalog.all.map { |benchmark| benchmark[:key].to_s }
    selected = Array(params[:benchmark_keys]).map(&:to_s).select { |key| all_keys.include?(key) }.uniq
    selected.empty? ? all_keys : selected
  end

  def fast_mode_enabled?
    ActiveModel::Type::Boolean.new.cast(params[:fast_mode])
  end
end
