class SynthesisRunsController < ApplicationController
  def index
    @synthesis_runs = SynthesisRun.order(created_at: :desc)
  end

  def show
    @synthesis_run = SynthesisRun.find(params[:id])
    @spectrum_result = SpectrumResult.find_by(synthesis_run_id: @synthesis_run.id)
  end

  def new
    @synthesis_run = SynthesisRun.new
    @catalog_targets = catalog_targets
    if @catalog_targets.any?
      @synthesis_run.sdss_ra ||= @catalog_targets.first.ra
      @synthesis_run.sdss_dec ||= @catalog_targets.first.dec
    end
  end

  def create
    @synthesis_run = SynthesisRun.new(synthesis_run_params)
    @synthesis_run.name = autogenerated_run_name if @synthesis_run.name.to_s.strip.empty?
    @synthesis_run.status = "pending"
    fetch_sdss = ActiveModel::Type::Boolean.new.cast(params[:fetch_sdss])
    manual_sdss_coordinates = ActiveModel::Type::Boolean.new.cast(params[:manual_sdss_coordinates])

    if fetch_sdss && !manual_sdss_coordinates
      selected_name = params[:sdss_catalog_target].to_s
      selected_target = catalog_targets.find { |target| target.name.to_s == selected_name }
      if selected_target
        @synthesis_run.sdss_ra = selected_target.ra
        @synthesis_run.sdss_dec = selected_target.dec
        @synthesis_run.galaxy_id = selected_target.id
      end
    end

    unless fetch_sdss
      @synthesis_run.sdss_ra = 0.0
      @synthesis_run.sdss_dec = 0.0
      @synthesis_run.galaxy_id = nil
    end

    if @synthesis_run.galaxy_id.nil? && fetch_sdss
      matched = Galaxy.find_by_ra_dec(@synthesis_run.sdss_ra, @synthesis_run.sdss_dec)
      @synthesis_run.galaxy_id = matched&.id
    end

    if @synthesis_run.save
      SynthesisPipelineJob.perform_later(@synthesis_run.id)
      redirect_to @synthesis_run, notice: "Synthesis run created."
    else
      @catalog_targets = catalog_targets
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    synthesis_run = SynthesisRun.find(params[:id])
    if %w[pending running].include?(synthesis_run.status.to_s)
      redirect_to synthesis_run_path(synthesis_run), alert: "Cannot delete a run while it is pending or running."
      return
    end

    synthesis_run.destroy!
    redirect_to synthesis_runs_path, notice: "Synthesis run deleted."
  end

  def seed_test
    target = Galaxy.where(agn: false).order(:name).to_a.sample
    target_name = target&.name || "fallback"
    target_ra = target&.ra || 187.2779
    target_dec = target&.dec || 2.0523
    target_id = target&.id
    sfh_model = %w[exponential delayed_exponential constant burst].sample
    spectra_model = %w[basel planck].sample
    imf_type = %w[kroupa salpeter chabrier].sample
    age_gyr = [1.0, 3.0, 5.0, 8.0, 10.0, 12.0].sample
    metallicity_z = [0.008, 0.02, 0.03].sample
    burst_age_gyr = sfh_model == "burst" ? [1.0, 2.0, 4.0, 8.0].sample : 2.0
    burst_width_gyr = sfh_model == "burst" ? [0.3, 0.5, 1.0].sample : 0.5
    wavelength_min = [300, 350, 400].sample
    wavelength_max = [800, 900, 1000].sample

    target_slug = target_name.to_s.downcase.gsub(/[^a-z0-9]+/, "_").gsub(/\A_+|_+\z/, "")
    run_name = [
      target_slug.presence || "target",
      abbreviate_sfh(sfh_model),
      abbreviate_imf(imf_type),
      abbreviate_spectra(spectra_model),
      "a#{age_gyr}",
      "z#{metallicity_z}",
      Time.current.strftime("%Y"),
      SecureRandom.hex(2)
    ].join("_")

    synthesis_run = SynthesisRun.create!(
      name: run_name,
      imf_type: imf_type,
      spectra_model: spectra_model,
      age_gyr: age_gyr,
      metallicity_z: metallicity_z,
      sfh_model: sfh_model,
      burst_age_gyr: burst_age_gyr,
      burst_width_gyr: burst_width_gyr,
      wavelength_min: wavelength_min,
      wavelength_max: wavelength_max,
      sdss_ra: target_ra,
      sdss_dec: target_dec,
      galaxy_id: target_id,
      status: "pending"
    )

    SynthesisPipelineJob.perform_later(synthesis_run.id)
    redirect_to synthesis_run_path(synthesis_run), notice: "Test run enqueued."
  end

  private

  def synthesis_run_params
    params.require(:synthesis_run).permit(
      :name,
      :imf_type,
      :spectra_model,
      :age_gyr,
      :metallicity_z,
      :sfh_model,
      :burst_age_gyr,
      :burst_width_gyr,
      :wavelength_min,
      :wavelength_max,
      :galaxy_id,
      :sdss_ra,
      :sdss_dec
    )
  end

  def catalog_targets
    @catalog_targets ||= Galaxy.where(agn: false).order(:name)
  end

  def autogenerated_run_name
    sfh_raw = params.dig(:synthesis_run, :sfh_model).presence || "sfh"
    imf_raw = params.dig(:synthesis_run, :imf_type).presence || "imf"
    spectra_raw = params.dig(:synthesis_run, :spectra_model).presence || "spectra"
    age = params.dig(:synthesis_run, :age_gyr).presence || "age"
    metallicity = params.dig(:synthesis_run, :metallicity_z).presence || "z"

    sfh = abbreviate_sfh(sfh_raw)
    imf = abbreviate_imf(imf_raw)
    spectra = abbreviate_spectra(spectra_raw)

    manual_sdss_coordinates = ActiveModel::Type::Boolean.new.cast(params[:manual_sdss_coordinates])
    base_target = manual_sdss_coordinates ? "" : params[:sdss_catalog_target].to_s.strip
    target_name =
      if base_target.present?
        base_target
      else
        ra = params.dig(:synthesis_run, :sdss_ra).presence
        dec = params.dig(:synthesis_run, :sdss_dec).presence
        (ra && dec) ? "ra#{ra}_dec#{dec}" : "target"
      end

    sanitized_target = target_name.downcase.gsub(/[^a-z0-9]+/, "_").gsub(/\A_+|_+\z/, "")
    year = Time.current.strftime("%Y")
    suffix = SecureRandom.hex(2)
    "#{sanitized_target}_#{sfh}_#{imf}_#{spectra}_a#{age}_z#{metallicity}_#{year}_#{suffix}"
  end

  def abbreviate_sfh(value)
    case value.to_s
    when "exponential" then "exp"
    when "delayed_exponential" then "dexp"
    when "constant" then "con"
    when "burst" then "bur"
    else value.to_s
    end
  end

  def abbreviate_imf(value)
    case value.to_s
    when "kroupa" then "kr"
    when "salpeter" then "sa"
    when "chabrier" then "ch"
    else value.to_s
    end
  end

  def abbreviate_spectra(value)
    case value.to_s
    when "basel" then "ba"
    when "planck" then "pl"
    else value.to_s
    end
  end
end
